config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "index#choose_license"
  get "index/choose_license"
  post "index/get_versions"
  post "index/new_license"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/license.rb
class License < ApplicationRecord
    validates :paid_till, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/index_controller.rb
require 'open-uri'
class IndexController < ApplicationController

    def choose_license; end

    def get_versions
        current_license = License.find_by(id: params[:license][:id])
        last_version_date = JSON.load(URI.open(API_ADDRESS)).to_a[0][1].to_date
        @version_arr = Array.new(5){ |i| last_version_date-i.month }
        @version_arr.select!{|el| el <= current_license.paid_till}
        if current_license.max_version
            max_version = (current_license.max_version.to_s.insert(0, '20') + '.01').to_date 
            @version_arr.select!{|el| el <= max_version.to_date}
        end
        if current_license.min_version
            min_version = (current_license.min_version.to_s.insert(0, '20') + '.01').to_date
            @version_arr.select!{|el| el >= min_version}
        end
        if !@version_arr.empty?
            @version_arr.map!{|el| el.strftime("%y.%m")}
        else
            @version_arr = current_license.paid_till.strftime("%y.%m")
            if max_version && max_version <= current_license.paid_till
                @version_arr = max_version.strftime("%y.%m")
            end
        end
    end

    def new_license
        new_date = (params["paid_till(1i)"]+'.'+ params["paid_till(2i)"] + '.' + params["paid_till(3i)"]).to_date
        License.create(paid_till: new_date, min_version: params[:min_version], max_version: params[:max_version],)
    end

    private

    API_ADDRESS = "http://localhost:4000/flussoniclastversion/get?format=json".freeze
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/index/choose_license.html.erb
<h1> CHOOSE LICENSE </h1>
<%= form_with url: index_get_versions_path, local: true do |f|%>
<%= collection_select(:license, :id, License.all, :id, :paid_till)%>
<%= f.button :submit%>
<% end %>
<h1> NEW LICENSE </h1>
<%= form_with url: index_new_license_path do |f| %>
  <%= f.label "Paid till:" %>
  <%= f.date_select :paid_till %>
  <%= f.label "Max version:" %>
  <%= f.text_field :max_version %>
  <%= f.label "Min version:" %>
  <%= f.text_field :min_version %>
  <%= f.button :submit%>
<% end %>

app/views/index/get_versions.html.erb
<h1> AVAILABLE VERSIONS </h1>
<%= @version_arr %>
<%= link_to "Back to choosing license", index_choose_license_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>